import NavBar from '@/components/navbar'
import Head from 'next/head'
import Dashboard from '@/components/dashboard'

export default function Home() {
  return (
    <div className='font-DM_Sans'>
      <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <Dashboard />
    </div>
  )
}
